apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebooks-irsa-account
  namespace: ebooks-app
---
apiVersion: v1
kind: Service
metadata:
  name: ebooks-service
  namespace: ebooks-app
spec:
  selector:
    app: ebooks-service
  ports:
  - port: 3002
    targetPort: 3002
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebooks-deployment
  namespace: ebooks-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ebooks-service
  template:
    metadata:
      labels:
        app: ebooks-service
    spec:
      serviceAccountName: ebooks-irsa-account
      containers:
      - name: ebooks
        image: adarshbarkunta/ebooks-service:27
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: S3_BUCKET
          valueFrom:
            secretKeyRef:
              name: s3-secret
              key: S3_BUCKET
        - name: AWS_REGION
          value: "ap-south-1"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_SECRET
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ebooks-hpa
  namespace: ebooks-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ebooks-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
